"""add notifications and project member invite status

Revision ID: 7ba371bea0ec
Revises: b0a174c4bf9f
Create Date: 2026-08-20 16:38:22.001052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ba371bea0ec'
down_revision: Union[str, None] = 'b0a174c4bf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    # 기존 행은 server_default 로 'active' 가 된다 — 이전 동작(초대=즉시 정식 멤버)과 동일하게
    # 유지되므로 이미 초대된 사람이 갑자기 접근을 잃지 않는다. responded_at 은 NULL 로 남는다.
    op.add_column('project_members', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('project_members', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'responded_at')
    op.drop_column('project_members', 'status')
    op.drop_index('ix_notifications_user_created_at', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
