"""add description to documents

Revision ID: 8f1ce77d1152
Revises: 3c8e4d489972
Create Date: 2026-08-14 16:42:41.411384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1ce77d1152'
down_revision: Union[str, None] = '3c8e4d489972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
