"""add rank to folders

Revision ID: 96dd7c952fde
Revises: a64b3ab130ae
Create Date: 2026-08-20 15:17:08.180709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dd7c952fde'
down_revision: Union[str, None] = 'a64b3ab130ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('rank', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # 기존 폴더는 같은 (project_id, parent_id) 안에서 id 순서를 그대로 rank로 백필한다
    op.execute(
        """
        UPDATE folders
        SET rank = ranked.rank
        FROM (
            SELECT
                id,
                (ROW_NUMBER() OVER (
                    PARTITION BY project_id, parent_id ORDER BY id
                ) - 1) * 1000 AS rank
            FROM folders
        ) AS ranked
        WHERE folders.id = ranked.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'rank')
    # ### end Alembic commands ###
