"""add project visibility and members

Revision ID: a64b3ab130ae
Revises: 72b852f975d6
Create Date: 2026-08-20 15:02:02.617568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64b3ab130ae'
down_revision: Union[str, None] = '72b852f975d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_project_members_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.add_column('projects', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.add_column('projects', sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False))
    op.create_foreign_key(op.f('fk_projects_owner_id_users'), 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # ── 데이터 백필 (DESIGN.md §28) ──
    # 기존 프로젝트는 이미 위에서 visibility='public' (server_default) 로 채워졌으니
    # 아무것도 안 바뀐다 — 여기선 owner_id 만 created_by(가입 당시 서버가 채운 사용자 id 문자열)에서
    # 역산해서 채우고, 그 owner 를 project_members 에도 owner role 로 등록해 멤버 목록이
    # create_project()로 새로 만든 프로젝트와 일관되게 보이도록 한다.
    op.execute(
        """
        UPDATE projects
        SET owner_id = CAST(created_by AS BIGINT)
        WHERE created_by ~ '^[0-9]+$'
          AND EXISTS (
              SELECT 1 FROM users WHERE users.id = CAST(projects.created_by AS BIGINT)
          )
        """
    )
    op.execute(
        """
        INSERT INTO project_members (project_id, user_id, role, invited_by, created_at)
        SELECT id, owner_id, 'owner', NULL, created_at
        FROM projects
        WHERE owner_id IS NOT NULL
        ON CONFLICT (project_id, user_id) DO NOTHING
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_owner_id_users'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'visibility')
    op.drop_column('projects', 'owner_id')
    op.drop_table('project_members')
    # ### end Alembic commands ###
