"""add level to document_sections

Revision ID: fed139dc629a
Revises: 9c02b71449b7
Create Date: 2026-08-14 17:18:49.078497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed139dc629a'
down_revision: Union[str, None] = '9c02b71449b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_sections', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_sections', 'level')
    # ### end Alembic commands ###
